apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-b-config
  namespace: default
data:
  CONNECT_BOOTSTRAP_SERVERS: "kafka-service:9092"
  CONNECT_GROUP_ID: "group-connector-b"
  CONNECT_CONFIG_STORAGE_TOPIC: "connector-b-configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "connector-b-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "connector-b-status"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_REST_ADVERTISED_HOST_NAME: "connector-b-service"
  CONNECT_REST_PORT: "8083"
  CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/java/plugins"
